version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - my_network

  nodejs:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql 
      DB_USER: root
      DB_PASSWORD: secret
      DB_DATABASE: test
    networks:
      - my_network
    depends_on:
      - mysql

networks:
  my_network:
    driver: bridge
