apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: green
  template:
    metadata:
      labels:
        app: backend
        version: green
    spec:
      containers:
      - name: backend
        image: ashwinircs06/backend:v0.05 # Replace with your Docker image path
        ports:
        - containerPort: 3000
---
