apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
      - name: backend
        image: ashwinircs06/backend:v0.05 # Replace with your Docker image path
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 31904
  type: NodePort
