kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
            defaultMode: 420
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
          ports:
            - name: es-http
              containerPort: 9200
              protocol: TCP
            - name: es-internal
              containerPort: 9300
              protocol: TCP
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: '-Xmx1g -Xms1g'
          resources: {}
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
          imagePullPolicy: IfNotPresent

---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 32462
  selector:
    app: elasticsearch
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    # Disable Elasticsearch security features
    xpack.security.enabled: false
    # Disable automatic creation of an enrollment token for Kibana instances
    xpack.security.enrollment.enabled: false
    # Disable SSL for HTTP communication
    xpack.security.http.ssl.enabled: false
    # Disable SSL for inter-node communication
    xpack.security.transport.ssl.enabled: false
