---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: blue
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
      - name: frontend-container
        image: ashwinircs06/frontend:v0.16 # Replace with your image path and tag
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32070
  type: NodePort

