apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
      - name: frontend-container
        image: ashwinircs06/frontend:v0.17 # Replace with your image path and tag
        ports:
        - containerPort: 3000
---
