kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      volumes:
        - name: config
          configMap:
            name: logstash-config
            defaultMode: 420
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.12.2
          ports:
            - containerPort: 5044
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf

---
kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5044
      targetPort: 5044
  selector:
    app: logstash
  type: ClusterIP
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        manage_template => false
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        # user => "elastic"
        # password => "changeme"
      }
    }
